spring:
  application:
    name: xiaolong
  datasource:
    url: jdbc:mysql://localhost:3306/xiaolong?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: chn123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    url: redis://@localhost:6379


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaolong.ssm.entity
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    org:
      springframework:
        web: DEBUG
        data:
          redis: info
      mybatis: DEBUG
    your.package.name: DEBUG
